apiVersion: v1 
kind: Service # The type of k8s resource, for this case a service.
metadata:
 name: alanp-eks-24aug-flask # Name of the service, a placeholder for the actual service.
spec:
 selector:
   app: alanp-eks-24aug-flask # The selector matches Pods with this label.
 ports:
   - port: 80 # The port that exposes this service to the world
     targetPort: 8000 # the port on the container that traffic will be forward to
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: alanp-eks-24aug-flask
spec:
 replicas: 1 
 selector:
   matchLabels:
     app: alanp-eks-24aug-flask
 template:
   metadata:
     labels:
       app: alanp-eks-24aug-flask
   spec:
     containers:
     - name: alanp-eks-24aug-flask
       image: public.ecr.aws/<your docker app url>V1 
       ports:
       - containerPort: 8000