apiVersion: v1
kind: Service
metadata:
 name: alanp-eks-24aug-world-flask
spec:
 selector:
   app: alanp-eks-24aug-world-flask
 ports:
   - port: 80
     targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment # Type of k8s resource
metadata:
 name: alanp-eks-24aug-world-flask # placeholder name
spec:
 replicas: 1 # 1 pod replica that is running
 selector:
   matchLabels:
     app: alanp-eks-24aug-world-flask # label selector to identify which Pod belongs to this
 template:
   metadata:
     labels:
       app: alanp-eks-24aug-world-flask # 
   spec:
     containers:
     - name: alanp-eks-24aug-world-flask
       image: public.ecr.aws/<your docker app url>V2
       ports:
       - containerPort: 8000