apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-route-alanp
  namespace: default
spec:
  parentRefs:
  - name: hello-alanp
    port: 80
  hostnames:
  - "default.us-east-1.elb.amazonaws.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: app1-flask
      port: 80
