apiVersion: v1 # Specifies the k8s API ver
kind: Pod # Defines resource type as "Pod"
metadata: # Metadata for the pod
  name: alanp-nginx-pod
spec: # Describes the desired state of the pod
  containers: # Single container using nginx latest image
  - name: alanp-nginx-pod
    image: nginx:latest
    ports:
    - containerPort: 80 # Container listen in on this port
