apiVersion: apps/v1 # Specifies the k8s API verson
kind: Deployment # Defines resource type as "Deployment"
metadata: # Contain metadata for the deployment
  name: alanp-2rep-nginx-deployment
spec: # Describe the desired state of the deployment
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # The template for each pods
    metadata:
      labels:
        app: nginx
    spec:
      containers: # Container name and using which image.
      - name: alanp-2rep-nginx-deployment
        image: nginx:latest
        ports:
        - containerPort: 80 # Container listens in on port 80

