name: AWS Secret and Variables Retrieval

on:
  push:
    branches:
      - main
      - master
      - feature/*
      - develop
  workflow_dispatch:

jobs:
  retrieve_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION_NAME }}

      # Insert secrets in AWS Secrets Manager, and retrieve based on the secret-id
      - name: Get Secret Object
        run: |
          secret_object=$(aws secretsmanager get-secret-value --secret-id alan_favorite_secrets --query SecretString --output json)
          # Parse specific keys from the secret object
          secret_value_favorite_food=$(echo "$secret_object" | jq -r '. | fromjson | .favorite_food')
          secret_value_favorite_drink=$(echo "$secret_object" | jq -r '. | fromjson | .favorite_drink')
          secret_value_favorite_dessert=$(echo "$secret_object" | jq -r '. | fromjson | .favorite_dessert')
          echo "Alan's favorite food is: $secret_value_favorite_food"
          echo "Alan's favorite drink is: $secret_value_favorite_drink"
          echo "Alan's favorite dessert is: $secret_value_favorite_dessert"

  retrieve_parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION_NAME }}

      # Insert parameters in AWS Systems Manager > Parameter Store, and retrieve them
      - name: Get Parameter Object
        run: |
          food_value=$(aws ssm get-parameter --name /alan/favorite_food --query Parameter.Value --output text)
          drink_value=$(aws ssm get-parameter --name /alan/favorite_drink --query Parameter.Value --output text)
          dessert_value=$(aws ssm get-parameter --name /alan/favorite_dessert --query Parameter.Value --output text)
          echo "Alan's favorite food from Parameter Store is: $food_value"
          echo "Alan's favorite drink from Parameter Store is: $drink_value"
          echo "Alan's favorite dessert from Parameter Store is: $dessert_value"
